### ISSUE TITLE
Update deployment comment to reflect the removal of `.../vk83/modules/access-models`

### ISSUE THREAD

**Issue by CodeGat** [ACCESS-NRI/build-cd#114]
Due to https://github.com/ACCESS-NRI/model-config-tests/pull/41#pullrequestreview-2229285965 making the module path `/g/data/vk83/modules/` instead of `/g/data/vk83/modules/access-models`, we need to update the deployment comment.

**Comment by aidanheerdegen** [comment]
I changed the priority, because it seems like an easy fix and something that could really confuse users.

Note that I've also change the `prerelease` modules to be the same because @dougiesquire bullied me into it.
