### ISSUE TITLE
Give current pre-release in the PR description

### ISSUE THREAD

**Issue by ccarouge** [ACCESS-NRI/build-cd#152]
Currently, when a pre-release is built, the action opens a new comment with the instructions to find the pre-release.

One downside of that approach is comments for previous pre-releases stay visible although the information is out-dated. This can lead to people trying to access an non-existent pre-release and get confused.

It might be better to give the information directly at the bottom of the PR description. It is easier to find and should allow to remove information to old pre-releases and only keep the current, existing release.

This is done to some extent for readthedocs previews in this action: https://github.com/readthedocs/actions

Here is what it looks like for readthedocs:
<img width="825" alt="Screenshot 2024-10-24 at 12 29 11 PM" src="https://github.com/user-attachments/assets/ed1a8214-43ba-4128-b1d6-49e8a07ae5aa">

**Comment by CodeGat** [comment]
Thanks Claire, getting onto this now. Just for some clarification, the prereleases are not non-existent when a new commit is pushed - all prereleases stay available until merge.
