### ISSUE TITLE
Spack packages built with different specs have the same modulefile name

### ISSUE THREAD

**Issue by harshula** [ACCESS-NRI/build-cd#157]
@chrisb13 reported the following:
https://github.com/ACCESS-NRI/ACCESS-OM2/pull/82#issuecomment-2434357382

@anton-seaice & @dougiesquire noticed that `module load` would pick the wrong `MOM5` Spack package. It looks like we need to make the modulefile names unique again.

Here's an example of a name collision:
```
$ find [...]/prerelease/apps/spack/0.22/release/modules/ -iname '2024.08.23'
[...]/prerelease/apps/spack/0.22/release/modules/linux-rocky8-x86_64/mom5/2024.08.23
[...]/prerelease/apps/spack/0.22/release/modules/linux-rocky8-x86_64_v4/mom5/2024.08.23
```

The default Spack configuration appends the Spack hash to the modulefile name.

**Comment by harshula** [comment]
**Attempted workaround in the modules section of `spack.yaml`**:

As soon as `hash_length` is non-zero. It automatically gets added to all module names regardless of
```
        projections:
          all: '{name}/{version}'
          access-om2: '{name}/2024.08.0'
```
I then tried setting hash_length to zero and hoping this would work:
```
        projections:
          all: '{name}/{version}-{hash}'
          access-om2: '{name}/2024.08.0'
```
but `{hash}` appears to be unsupported:
```
==> Error: some tokens cannot be part of the module naming scheme [hash]. Did you check your 'modules.yaml' configuration?
```
lib/spack/spack/modules/common.py:
```
#: Valid tokens for naming scheme and env variable names
_valid_tokens = (
    "name",
    "version",
    "compiler",
    "compiler.name",
    "compiler.version",
    "architecture",
    # tokens from old-style format strings
    "package",
    "compilername",
    "compilerver",
)
```

**Comment by CodeGat** [comment]
Thoughts on implementation details:

A post-processing renaming of module directories should happen after installation via `spack`. This happens in `.github/workflows/deploy-2-start.yml`, job `deploy-to-environment`, after step `Deploy to ${{ inputs.deployment-environment }}`. 

If this is how it's going to go, we might need a similar `ssh` invocation. There should be enough to go on with the environment variables already defined at the job level. Might be difficult to get the modules that need to be changed - could try `yq`ing the `.spack.modules.default.tcl.projections` as a start on what module directories need to be modified.

**Comment by harshula** [comment]
This syntax doesn't work:
```
all: '{name}/{version}-{hash}'
```

This syntax does work:
```
all: '{name}/{version}-{hash:7}'
```

**Comment by harshula** [comment]
notabug
We have a solution.

**Comment by harshula** [comment]
Reopening this issue to track all the model deployment repositories that need to be modified, including the template (https://github.com/ACCESS-NRI/model-deployment-template).

**Comment by aidanheerdegen** [comment]
Repo list:

- [ ] https://github.com/ACCESS-NRI/ACCESS-TEST
- [ ] https://github.com/ACCESS-NRI/ACCESS-OM2
- [ ] https://github.com/ACCESS-NRI/CABLE-standalone
- [ ] https://github.com/ACCESS-NRI/ACCESS-OM3
- [ ] https://github.com/ACCESS-NRI/ACCESS-ESM1.5
- [ ] https://github.com/ACCESS-NRI/ACCESS-ESM1.6
- [ ] https://github.com/ACCESS-NRI/model-deployment-template

**Comment by harshula** [comment]
Looks like there are changes that need to be made to build-cd to accommodate our preferred format:
```
Error: cice5: Version of dependency and projection do not match (2023.10.19 != 2023.10.19-{hash:7})
Error: mom5: Version of dependency and projection do not match (2024.08.23 != 2024.08.23-{hash:7})
Error: libaccessom2: Version of dependency and projection do not match (2023.10.26 != 2023.10.26-{hash:7})
Error: oasis3-mct: Version of dependency and projection do not match (2023.11.09 != 2023.11.09-{hash:7})
Error: Process completed with exit code 1.
```

Our preferred format:
```
          cice5: '{name}/2023.10.19-{hash:7}'
          mom5: '{name}/2024.08.23-{hash:7}'
          libaccessom2: '{name}/2023.10.26-{hash:7}'
          oasis3-mct: '{name}/2023.11.09-{hash:7}'
```

**Comment by CodeGat** [comment]
@harshula those changes that are needed in the CD have been done in https://github.com/ACCESS-NRI/build-cd/pull/158

**Comment by CodeGat** [comment]
See subissues for the repos that require the updates.

**Comment by CodeGat** [comment]
@harshula , does this close off the issue?
