### ISSUE TITLE
Intel compiler hard-coded into deployment

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/build-cd#17]
The deployment workflow hard-codes `module load intel-compiler/2019.5.281`:

https://github.com/ACCESS-NRI/build-cd/blob/main/.github/workflows/deploy-2-start.yml#L52

If it has any effect (I don't think it does) then it should be removed.

It it has no effect (whichI believe it doesn't) then it should also be removed.

@harshula?

**Comment by harshula** [comment]
Can spack_config be used instead?

**Comment by harshula** [comment]
CD may need a different `spack_config/config/config.yaml`.
