### ISSUE TITLE
spack.yaml: allow the specs section to contain variants

### ISSUE THREAD

**Issue by harshula** [ACCESS-NRI/build-cd#180]
Due to `build-cd` not allowing variants in the specs section, this type of hack is required: https://github.com/ACCESS-NRI/spack-packages/commit/84a010b752d07fbbf8536b63a8ac4b11ec61a26f in the SBRs. i.e. A separate branch had to be created to allow building the variant.

**Comment by CodeGat** [comment]
Closing this as the PRs linked are closed
