### ISSUE TITLE
Restricting access to deployed models containing UM or other UKMO licensed software

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/build-cd#45]
We have an obligation to restrict access to [UKMO](https://www.metoffice.gov.uk) software products that are covered by a restricted license. This includes the Unified Atmosphere (UM), so ACCESS-ESM1.5, ACCESS-CM2 and ACCESS-AM.

We will do this by adding ACLs to restrict access to a directory tree to users in the [`ki32_mosrs`](https://my.nci.org.au/mancini/project/ki32_mosrs) group at NCI. 

NCI vet anyone who wishes to use UKMO licensed software at NCI before allowing them to join `ki32_mosrs`. In this way we can be sure that anyone who is a member of that group is allowed access to compiled and deployed ACCESS models that contain the UM.

I think the easiest way to do this is to have an entirely separate deployment directory with the ACLs set at that top level. I guess it would mean there would be an `apps` and `prerelease` under that top level.

However, only a small number of components (UM, gcom) are restrictively licensed, so it would be nice if the restrictions only applied to them. It would be difficult though, as all intermediate build steps would need to also restrict access to those packages and their sources.

**Comment by CodeGat** [comment]
Cool. In terms of location:
* What parts of the UM are restrictively licensed? Is it the built artefact, the source code, intermediate objects? Would the spack.yaml be restricted if there are special flags that are used to compile the UM? These questions will inform what we can put into `/scratch` (or just out of the restricted area). 
* So where would we put this separate deployment directory? Would it still be under the `vk83` project? Would it contain it's own installs of spack? 
Restricting the deployment location based on whether they have restricted stuff in them should be more than fine - just need to create a `Gadi (restricted/UM/TOP SECRET!!)` GitHub environment and pass that name to the regular deployment workflow. Easy :)

**Comment by aidanheerdegen** [comment]
> * What parts of the UM are restrictively licensed? Is it the built artefact, the source code, intermediate objects? 

All of the above.

> Would the spack.yaml be restricted if there are special flags that are used to compile the UM? 

No. There aren't and we really want to try and stop the creeping secrecy bug that infects everything the UM touches.

> These questions will inform what we can put into `/scratch` (or just out of the restricted area).

Pretty much nothing that is the UM or gcom (might have to check with the latter, but I believe it was also touched the secrecy "poo stick".

> * So where would we put this separate deployment directory? Would it still be under the `vk83` project? Would it contain its own installs of spack?

Yes under `vk83`. Shouldn't need a separate `spack` install unless that was required for technical reasons (*waves hands*)

> Restricting the deployment location based on whether they have restricted stuff in them should be more than fine - just need to create a `Gadi (restricted/UM/TOP SECRET!!)` GitHub environment and pass that name to the regular deployment workflow. Easy :)

Sweet! As I said, making a separate directory tree is probably the most straightforward, but it will mean duplication. So nasty but 🤷

**Comment by CodeGat** [comment]
> Shouldn't need a separate `spack` install unless that was required for technical reasons (_waves hands_)

The issue that I wonder about is the intermediate objects that `spack` might generate regarding the UM/gcom that you've noted are restricted - for example, the environments are under `$spack/var/spack/environments/` which anyone can access. I think there are also build log files that are under the users (`tm70_ci`) home directory, for whatever reason. Maybe we'd need a separate spack install...?

**Comment by CodeGat** [comment]
@harshula pinging here for a potential meeting on the subject

**Comment by CodeGat** [comment]
@aidanheerdegen you can modify the install tree via the `spack.yaml` like so (similar to the `config.yaml`):
```yaml
spack:
  config:
    install_tree:
      root: "$spack/../restricted_release"
    build_stage: "/g/data/tm70/tm70_ci/restricted_build_stage"
```

**Comment by aidanheerdegen** [comment]
SWEET!

**Comment by CodeGat** [comment]
What should we call the restricted release? Currently:
```
/g/data/vk83/apps/spack/0.20/
├── spack
├── spack-packages
├── spack-config
├── release
└── release-restricted-ukmo
```
Going with `release-restricted-ukmo` just in case there are any future models that may restrict parts (but are restricted to a different class of users). We can also have something like `release-restricted` if we wanted to be more general.

**Comment by CodeGat** [comment]
From a meeting with @harshula and @aidanheerdegen:
* We will add UKMO-restricted `spack config` to spack.yaml`
* We will create the restricted directories below as part of inital spack creation
* We will add the following structure:

```
/g/data/vk83/apps/spack/0.20/
├── spack
├── spack-packages
├── spack-config
├── release
└── restricted/
    └── ukmo/
        ├── release
        └── source_cache
```

**Comment by CodeGat** [comment]
Closing this as all the linked PRs and issues have been closed. We have created restricted locations for `ACCESS-ESM1.5` to be deployed.
