### ISSUE TITLE
Investigate whether we should have a `yaml` schema for our flavour of `spack.yaml`

### ISSUE THREAD

**Issue by CodeGat** [ACCESS-NRI/build-cd#55]
Our `spack.yaml`s seem to have a particular shape. They all so far require:
* a single line in the `.spack.specs` section, where the root SBD resides
* customisation of the packages and dependencies from within the `.spack.packages` section
* some of the versions that are a projection must match the versions that we specify in the `.spack.[packages|specs]` section 

Maybe we should validate this with a proper tool, similar to what we do with the `jsonschema` stuff. Then we can point people to their errors are, if we have a particular format. It'd simplify all the checks we do on the `spack.yaml` in the CI, too. 

Pinging @aidanheerdegen as well

**Comment by aidanheerdegen** [comment]
I ❤️ this idea.

💯 

👍 

🥇

**Comment by aidanheerdegen** [comment]
So yeah absolutely on-board with validating with `json-schema` and we should also put it in the [official schema repo](https://github.com/ACCESS-NRI/schema).

**Comment by CodeGat** [comment]
In order to get the validation schema that `spack` uses, I ran (in `access-nri/spack`):
```bash
spack python
```
which allows one to run spack as if one was in a python integrated environment. 
I then ran:
```py
from spack.schema.env import schema
print(schema)
```
as it had a bunch of variables to construct the schema that I couldn't be bothered tracking down. 
Then had to convert all the python-isms to proper json and format it correctly. The schema is definitely autogenerated, because it is massive.

**Comment by aidanheerdegen** [comment]
Wow! Very clever, and kinda cool you can just pop the hood and rev spack a bit to spit out what you want (terrible analogy, but you get the point).

At the risk of suggesting this a bit late, I don't think we need to have a general schema for `spack.yaml`, but one that matches exactly our use case. Does that make sense?

**Comment by CodeGat** [comment]
More notes: We should use https://github.com/ajv-validator/ajv-cli for validation on the runner (`jsonschema` doesn't support validation of `yaml`) which you can get with `npm install -g ajv-cli` and validate with `ajv -s /path/to/schema.json -d /path/to/data.yaml --strict=false`. We put `strict=false` because that is used for validation of the schema, not validation of the data.
